use_frameworks!

platform :ios, '9.0'

target 'CZCommonLib_Example' do
    pod 'CZCommonLib', :path => '../'
    pod 'WechatOpenSDK', '~> 1.8.3'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
  target 'CZCommonLib_Tests' do
    inherit! :search_paths
  end
end
